import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from 'next/link';
import NavBar from './NavBar';
import "./globals.css";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <a href="#main-content" className="sr-only focus:not-sr-only absolute top-4 left-4 bg-accent text-white px-3 py-2 rounded">Skip to main content</a>
        <header className="bg-white/80 dark:bg-neutral/80 backdrop-blur shadow-sm sticky top-0 z-50 border-b border-gray-200 dark:border-neutral transition-all duration-300">
          <NavBar />
        </header>
        {children}
        {/* Footer Section */}
        <footer className="bg-black pt-8 pb-6 mt-12">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center text-white">
            <p className="text-sm"> {new Date().getFullYear()} AIC-ABA. All rights reserved.</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
